name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: jscpd-copy-paste-detector
        uses: kucherenko/jscpd@v5.0.16
        with:
          args: "--threshold 0"